# Generated by Django 4.2.5 on 2023-09-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0002_alter_user_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='games',
        ),
        migrations.AddField(
            model_name='user',
            name='games',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='proj.game'),
        ),
    ]
