# Generated by Django 4.2.5 on 2023-09-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0003_remove_user_games_user_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='games',
            field=models.ManyToManyField(to='proj.game'),
        ),
    ]
